#!/bin/bash

mkdir ~/Desktop/youtube-video-playlist
cd ~/Desktop/youtube-video-playlist

read -p "YouTube's playlist URL : " url

read -p "Enter the videos numbers (ex : 1-3,5-6) : " num

# Download all the playlist's videos
yt-dlp -f 'bestvideo+bestaudio' --recode-video mp4 --yes-playlist --playlist-items -o "%(title)s.%(ext)s" "${num}" "${url}"